apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        run: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet: 
              path: /
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 15