apiVersion: v1
kind: Service
metadata:
  name: acheezable
  labels:
    run: acheezable
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    run: acheezable
  type: NodePort
